version: '3.9'
services:
  db:
    image: postgres:15
    container_name: etnair_db
    environment:
      POSTGRES_USER: etnair_user
      POSTGRES_PASSWORD: etnair_pass
      POSTGRES_DB: etnair_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - etnair_network

  api:
    build:
      context: ./api
    container_name: etnair_api
    environment:
      DB_HOST: db
      DB_USER: etnair_user
      DB_PASSWORD: etnair_pass
      DB_NAME: etnair_db
    ports:
      - "3000:3000"
    networks:
      - etnair_network

volumes:
  db_data:

networks:
  etnair_network:
  